# Generated by Django 2.2.3 on 2019-08-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190809_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='autor',
            new_name='author',
        ),
    ]
